artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: knkarthick/samsum
  save_dir: artifacts/data_ingestion/samsum

data_transformation:
  root_dir: dt
  data_path: artifacts/data_ingestion/samsum
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: mt
  data_path: dt/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: me
  data_path: dt/samsum_dataset
  model_path: mt/pegasus-samsum-model
  tokenizer_path: mt/tokenizer
  metric_file_name: me/metrics.csv

  